#!/usr/bin/env bash

#
#
# Configure Screen saver to 15 mins - PCI DSS requirement
defaults -currentHost write com.apple.screensaver idleTime 600

# Require password immediately after sleep or screen saver begins
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# Empty Trash securely by default
defaults write com.apple.finder EmptyTrashSecurely -bool true
